replace fetcher

diff --git a/extension/benchmark/android/benchmark/android-llm-device-farm-test-spec.yml.j2 b/extension/benchmark/android/benchmark/android-llm-device-farm-test-spec.yml.j2
--- a/extension/benchmark/android/benchmark/android-llm-device-farm-test-spec.yml.j2
+++ b/extension/benchmark/android/benchmark/android-llm-device-farm-test-spec.yml.j2
@@ -11,7 +11,12 @@ phases:
       # Print this so that the upload script can read and process the benchmark config
       - echo "The benchmark config is {{ benchmark_config_id }}"
 
-      # Download the model from S3
+      - echo "Checking if model exists in S3..."
+      - |
+        if ! curl -s --fail -I '{{ model_path }}'; then
+          echo "model file not found in S3. Exiting test."
+          exit 1
+        fi
       - curl -s --fail '{{ model_path }}' -o model.zip
       - unzip model.zip && ls -la
 
