Match PyTorch _link_check.yml (#10709)

diff --git a/.github/workflows/_link_check.yml b/.github/workflows/_link_check.yml
--- a/.github/workflows/_link_check.yml
+++ b/.github/workflows/_link_check.yml
@@ -12,10 +12,10 @@ jobs:
     with:
       runner: linux.2xlarge
       docker-image: executorch-ubuntu-22.04-linter
-      submodules: 'none'
+      submodules: false
       fetch-depth: 0
       ref: ${{ inputs.ref }}
-      timeout: 90
+      timeout: 120
       script: |
         ./scripts/lint_urls.sh $(
           { [ "${{ github.event_name }}" = "pull_request" ] \
@@ -23,7 +23,13 @@ jobs:
           || \
           { [ "${{ github.event_name }}" = "push" ] \
               && git diff --name-only "${{ github.event.before }}...${{ github.sha }}"; }
-        )
+        ) || {
+          echo
+          echo "URL lint failed."
+          echo "If this is a transient outage, you can bypass it by adding the \`skip-url-lint\` label to your PR."
+          echo "Or add \`@lint-ignore\` somewhere on the same line as the URL you want to skip checking."
+          exit 1
+        }
 
   lint-xrefs:
     if: ${{ github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'skip-xref-lint') }}
@@ -31,10 +37,10 @@ jobs:
     with:
       runner: linux.2xlarge
       docker-image: executorch-ubuntu-22.04-linter
-      submodules: 'none'
+      submodules: false
       fetch-depth: 0
       ref: ${{ inputs.ref }}
-      timeout: 90
+      timeout: 60
       script: |
         ./scripts/lint_xrefs.sh $(
           { [ "${{ github.event_name }}" = "pull_request" ] \
@@ -42,4 +48,10 @@ jobs:
           || \
           { [ "${{ github.event_name }}" = "push" ] \
               && git diff --name-only "${{ github.event.before }}...${{ github.sha }}"; }
-        )
+        ) || {
+          echo
+          echo "Xref lint failed."
+          echo "If this is a transient outage, you can bypass it by adding the \`skip-xref-lint\` label to your PR."
+          echo "Or add \`@lint-ignore\` somewhere on the same line as the reference you want to skip checking."
+          exit 1
+        }
