Update doc build job to publish stable tags (#740)
Summary:
Pull Request resolved: https://github.com/pytorch/executorch/pull/740

Update the build job to publish versioned docs.

Reviewed By: dbort

Differential Revision: D50023237

fbshipit-source-id: c97dddcae372231a1409fcfbf7970ebe7db66254

diff --git a/.github/workflows/doc-build.yml b/.github/workflows/doc-build.yml
--- a/.github/workflows/doc-build.yml
+++ b/.github/workflows/doc-build.yml
@@ -7,6 +7,7 @@ on:
       - main
       - release/*
     tags:
+      - stable-*
       - v[0-9]+.[0-9]+.[0-9]
       - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
   workflow_dispatch:
@@ -33,7 +34,7 @@ jobs:
         conda activate "${CONDA_ENV}"
 
         BUILD_TOOL=${{ matrix.build-tool }}
-        # Setup MacOS dependencies as there is no Docker support on MacOS atm
+        # Setup dependencies as there is no Docker support
         PYTHON_EXECUTABLE=python bash .ci/scripts/setup-linux.sh "${BUILD_TOOL}"
 
         if [[(${GITHUB_EVENT_NAME} = 'pull_request' && (${GITHUB_BASE_REF} = 'release'*)) || (${GITHUB_REF} = 'refs/heads/release'*) ]]; then
@@ -64,26 +65,41 @@ jobs:
 #    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
 
   upload-gh-pages:
-    if: ${{ (github.repository == 'pytorch/executorch') && (github.ref_name == 'main') }}
+    if: github.repository == 'pytorch/executorch' && github.event_name == 'push' &&
+        ((github.ref_type == 'branch' && github.ref_name == 'main') || github.ref_type == 'tag')
     permissions:
       contents: write
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-    - uses: actions/checkout@v3
-      with:
-        ref: gh-pages
-    - uses: actions/download-artifact@v3
-      with:
-        name: docs
-    - name: Upload docs
-      run: |
+    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
+    with:
+      repository: pytorch/executorch
+      download-artifact: docs
+      ref: gh-pages
+      script: |
+        set -euo pipefail
 
-        set -x
+        REF_TYPE=${{ github.ref_type }}
+        REF_NAME=${{ github.ref_name }}
+
+        # If building for a release tag, branch, set the branch/tag name
+        # as the target folder in the gh-pages branch. The artifacts created
+        # during the build will be copied over to the target dir in the
+        # gh-pages branch.
+        if [[ "${REF_TYPE}" == branch || "${REF_TYPE}" == tag ]]; then
+          TARGET_FOLDER="${REF_NAME}"
+        else
+          echo "ERROR: Invalid REF_TYPE: ${REF_TYPE}. Expected 'branch' or 'tag'."
+          exit 1
+        fi
+        echo "Target Folder: ${TARGET_FOLDER}"
+
+        mkdir -p "${TARGET_FOLDER}"
+        # Clean up target folder if exists and copy html output to the
+        # Target folder
+        rm -rf "${TARGET_FOLDER}"/*
+        mv "${RUNNER_ARTIFACT_DIR}"/html/* "${TARGET_FOLDER}"
+        git add "${TARGET_FOLDER}" || true
+
         git config user.name 'pytorchbot'
         git config user.email 'soumith+bot@pytorch.org'
-        rm -rf main
-        mv html main
-        git add --all main || true
         git commit -m "Auto-generating sphinx docs" || true
         git push -f
