[llava][9/N] Add an option to turn on/off sdpa_with_kv_cache
Summary: As titled, need to test both options in export_llava.py.

Test Plan: Added CI job

Reviewers:

Subscribers:

Tasks:

Tags:

ghstack-source-id: 8964d9befce352a621157f3952d64ca7bc4128f0
Pull Request resolved: https://github.com/pytorch/executorch/pull/4444

diff --git a/.github/workflows/pull.yml b/.github/workflows/pull.yml
--- a/.github/workflows/pull.yml
+++ b/.github/workflows/pull.yml
@@ -210,11 +210,19 @@ jobs:
         bash examples/models/llava/install_requirements.sh
 
         # run export_llava.sh
-        python examples/models/llava/export_llava.py
+        python examples/models/llava/export_llava.py --use-sdpa-with-kv-cache --pte-name llava_custom_sdpa.pte
 
         # verify file exists
-        if [ ! -f "llava_combined_xnnpack.pte" ]; then
-            echo "llava_combined_xnnpack.pte not found!"
+        if [ ! -f "llava_custom_sdpa.pte" ]; then
+            echo "llava_custom_sdpa.pte not found!"
+            exit 1
+        fi
+
+        python examples/models/llava/export_llava.py --no-use-sdpa-with-kv-cache --pte-name llava.pte
+
+        # verify file exists
+        if [ ! -f "llava.pte" ]; then
+            echo "llava.pte not found!"
             exit 1
         fi
 
