Test seems to have passed, adding some error checking and clean up

diff --git a/.github/workflows/trunk.yml b/.github/workflows/trunk.yml
--- a/.github/workflows/trunk.yml
+++ b/.github/workflows/trunk.yml
@@ -75,8 +75,6 @@ jobs:
 
         source .ci/scripts/utils.sh
         mkdir -p zephyr_scratch/
-        pwd
-        ls
         cd zephyr_scratch
         export ZEPHYR_PROJ_ROOT=$(realpath $(pwd))
 
@@ -94,26 +92,21 @@ jobs:
         west init -l zephyr
         west config manifest.project-filter -- +executorch
         west -v update
-        pwd
-        ls
 
         cd $ZEPHYR_PROJ_ROOT/modules/lib/executorch
-        #python3 -m venv .venv && source .venv/bin/activate && pip install --upgrade pip
         install_executorch "--use-pt-pinned-commit"
         .ci/scripts/setup-arm-baremetal-tools.sh --target-toolchain zephyr
         source examples/arm/ethos-u-scratch/setup_path.sh
-        pwd
-        ls
         cd $ZEPHYR_PROJ_ROOT
-        pwd
-        ls
         source zephyr/zephyr-env.sh
         cd $ZEPHYR_PROJ_ROOT/zephyr/samples/modules/executorch/arm/hello_world
         west build -p always -b mps3/corstone300/fvp
         FVP_Corstone_SSE-300_Ethos-U55 -a build/zephyr/zephyr.elf -C mps3_board.visualisation.disable-visualisation=1 -C mps3_board.telnetterminal0.start_telnet=0 -C mps3_board.uart0.out_file='sim.out'  -C cpu0.CFGITCMSZ=15 -C cpu0.CFGDTCMSZ=15 --simlimit 60
-        pwd
-        ls
+
         cat sim.out
+        grep -q "Output[0][0]: (float) 2.000000" sim.out; then
+        exit_status=$? #store 0 if found (success), 1 if not (failure)
+        exit $exit_status
 
   test-models-linux-aarch64:
     name: test-models-linux-aarch64
