Arm backend: Split ZephyrOS tests per target
Split ZephyrOS tests per target so tests can run separate if wanted
and add support to run multipe tests after setup if you want to run
them all localy.

This removed the allowpattern as it would not stop bad code anyway
but gives the false impression that it does, removing the check also
make the code more easy to understant.

This also introduces invisible tags in the README.md in the form of
<!-- RUN TAGNAME -->
To make the parsing a bit more machine friendly and to make it easier
to change the readable text without strange test side effects.

Signed-off-by: Zingo Andersen <Zingo.Andersen@arm.com>
Change-Id: I69285db4c7d99febd53becaedc5afa83321731fc

diff --git a/.github/workflows/trunk.yml b/.github/workflows/trunk.yml
--- a/.github/workflows/trunk.yml
+++ b/.github/workflows/trunk.yml
@@ -59,6 +59,8 @@ jobs:
     name: test-arm-backend-zephyr
     uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
     strategy:
+      matrix:
+        target: [ethos-u55, cortex-m55, ethos-u85]
       fail-fast: false
     with:
       runner: linux.2xlarge
@@ -75,6 +77,13 @@ jobs:
         # Test zephyr backend
         set -e
 
+        # Support comma-separated TARGET_LIST or ${{ matrix.target }} list, e.g., TARGET_LIST="ethos-u55,cortex-m55,ethos-u85"
+        if [ -z "${TARGET_LIST:-}" ]; then
+          IFS=',' read -r -a TARGETS <<< "${{ matrix.target }}"
+        else
+          IFS=',' read -r -a TARGETS <<< "${TARGET_LIST}"
+        fi
+
         export EXECUTORCH_PROJ_ROOT=$(realpath $(pwd))
 
         # Source utility scripts
@@ -86,9 +95,7 @@ jobs:
 
         # Based on instruction in zephyr/README.md
 
-        # Allowed only "pip install ..." commands
-        allowedpattern='^(pip|pip3)[[:space:]]+install([[:space:]].*)?$'
-        run_command_block_from_zephyr_readme 'Install requirements' "${allowedpattern}"
+        run_command_block_from_zephyr_readme "<!-- RUN install_reqs -->"
 
         # Make sure to backup the zephyr_scratch folder if it exists to allow for local
         # testing that does not lose code/data
@@ -121,13 +128,11 @@ jobs:
 
         cd ${ZEPHYR_PROJ_ROOT}
 
-        # Allowed only "west init ..." commands
-        run_command_block_from_zephyr_readme 'Setup zephyr repo' '^west[[:space:]]+init([[:space:]].*)?$'
+        run_command_block_from_zephyr_readme "<!-- RUN west_init -->"
 
         cp ${EXECUTORCH_PROJ_ROOT}/zephyr/executorch.yaml zephyr/submanifests/
 
-        # Allowed only "west ..." commands
-        run_command_block_from_zephyr_readme 'Add ExecuTorch to Zephyr' '^west([[:space:]].*)?$'
+        run_command_block_from_zephyr_readme "<!-- RUN west_config -->"
 
         # Switch to executorch in this PR e.g. replace modules/lib/executorch with the root folder of this repo
         # instead of doing a re-checkout and figure out the correct commit hash etc
@@ -143,52 +148,34 @@ jobs:
           git config --global user.email "github_executorch@arm.com"
         fi
 
-        # Allowed only "cd/git/install_executorch.sh" commands
-        run_command_block_from_zephyr_readme 'Setup ExecuTorch' '^(cd [^;&|]+|git submodule([[:space:]].*)?|\./install_executorch\.sh([[:space:]].*)?)$'
+        run_command_block_from_zephyr_readme "<!-- RUN install_executorch -->"
 
-        # As "cd" was an allowed command in the last run_command_block_from_zephyr_readme
-        # lets ensure we are back to the expected folder
-        cd ${ZEPHYR_PROJ_ROOT}
+        run_command_block_from_zephyr_readme "<!-- RUN install_arm_tools -->"
 
-        # Allowed only "examples/arm/setup.sh and source of the generated script" command
-        run_command_block_from_zephyr_readme 'Install TOSA, vela and FVPs' '^(modules/lib/executorch/examples/arm/setup\.sh([[:space:]].*)?|(source|\.) modules/lib/executorch/examples/arm/arm-scratch/setup_path\.sh)$'
+        for TARGET in "${TARGETS[@]}"; do
+          TARGET="$(echo "$TARGET" | xargs)" # trim whitespace
 
-        echo "===== Corstone300 FVP setup ===="
+          echo "---- ${TARGET} ----"
+          rm -Rf build
 
-        # Allowed only "export" command
-        run_command_block_from_zephyr_readme 'Config Zephyr Corstone300 FVP' '^export([[:space:]].*)$'
+          if [[ ${TARGET} == "ethos-u55" || ${TARGET} == "cortex-m55" ]]; then
+            BOARD="corstone300"
+          elif [[ ${TARGET} == "ethos-u85" ]]; then
+            BOARD="corstone320"
+          else
+            echo "Fail unsupport target selection ${TARGET}"
+            exit 1
+          fi
 
-        echo "---- Ethos-U55 ----"
-        rm -Rf build
+          echo "---- ${TARGET} Board ${BOARD} FVP setup ----"
+          run_command_block_from_zephyr_readme "<!-- RUN setup_${BOARD}_fvp -->"
 
-        # Allowed only "aot_arm_compiler" command
-        run_command_block_from_zephyr_readme 'Prepare the Ethos-U55 PTE model' '^python -m modules.lib.executorch.examples.arm.aot_arm_compiler([[:space:]].*)?$'
+          echo "---- ${TARGET} Create PTE ----"
+          run_command_block_from_zephyr_readme "<!-- RUN test_${TARGET}_generate_pte -->"
 
-        # Allowed only "west build" command
-        run_command_block_from_zephyr_readme 'Run the Ethos-U55 PTE model' '^west build([[:space:]].*)?$'
-
-        echo "---- Cortex-M55 ----"
-        rm -Rf build
-
-        # Allowed only "aot_arm_compiler" command
-        run_command_block_from_zephyr_readme 'Prepare the Cortex-M55 PTE model' '^python -m modules.lib.executorch.examples.arm.aot_arm_compiler([[:space:]].*)?$'
-
-        # Allowed only "west build" command
-        run_command_block_from_zephyr_readme 'Run the Cortex-M55 PTE model' '^west build([[:space:]].*)?$'
-
-        echo "===== Corstone320 FVP setup ===="
-
-        # Allowed only "export" command
-        run_command_block_from_zephyr_readme 'Config Zephyr Corstone320 FVP' '^export([[:space:]].*)$'
-
-        echo "---- Ethos-U85 ----"
-        rm -Rf build
-
-        # Allowed only "aot_arm_compiler" command
-        run_command_block_from_zephyr_readme 'Prepare the Ethos-U85 PTE model' '^python -m modules.lib.executorch.examples.arm.aot_arm_compiler([[:space:]].*)?$'
-
-        # Allowed only "west build" command
-        run_command_block_from_zephyr_readme 'Run the Ethos-U85 PTE model' '^west build([[:space:]].*)?$'
+          echo "---- ${TARGET} Build and run ----"
+          run_command_block_from_zephyr_readme "<!-- RUN test_${TARGET}_build_and_run -->"
+        done
 
   test-models-linux-aarch64:
     name: test-models-linux-aarch64
