up

diff --git a/.github/workflows/trunk.yml b/.github/workflows/trunk.yml
--- a/.github/workflows/trunk.yml
+++ b/.github/workflows/trunk.yml
@@ -799,6 +799,96 @@ jobs:
 
         echo "::endgroup::"
 
+  test-huggingface-transformers-coreml:
+    # NB: Don't run this on fork PRs because they won't have access to the secret and would fail anyway
+    if: ${{ !github.event.pull_request.head.repo.fork }}
+    name: test-huggingface-transformers-coreml
+    uses: pytorch/test-infra/.github/workflows/macos_job.yml@main
+    permissions:
+      id-token: write
+      contents: read
+    secrets: inherit
+    strategy:
+      matrix:
+        hf_model_id: [
+          Qwen/Qwen3-0.6B,
+          HuggingFaceTB/SmolLM2-135M,
+          meta-llama/Llama-3.2-1B,
+          allenai/OLMo-1B-hf,
+        ]
+      fail-fast: false
+    with:
+      secrets-env: EXECUTORCH_HF_TOKEN
+      runner: macos-15-xlarge
+      python-version: '3.11'
+      submodules: 'recursive'
+      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
+      timeout: 90
+      upload-artifact: profiling-artifacts-${{ strategy.job-index }}
+      script: |
+        set -eux
+        echo "::group::Set up ExecuTorch"
+        bash .ci/scripts/setup-conda.sh
+        eval "$(conda shell.bash hook)"
+
+        # Install requirements
+        ${CONDA_RUN} python install_executorch.py
+        echo "::endgroup::"
+
+        echo "::group::Set up Hugging Face"
+        pip install -U "huggingface_hub[cli]"
+        huggingface-cli login --token $SECRET_EXECUTORCH_HF_TOKEN
+        OPTIMUM_ET_COMMIT=$(cat .ci/docker/ci_commit_pins/optimum-executorch.txt)
+        git clone https://github.com/huggingface/optimum-executorch
+        pushd optimum-executorch
+        # There is no release yet, for CI stability, always test from the same commit on main
+        git checkout $OPTIMUM_ET_COMMIT
+        python install_dev.py --skip_override_torch
+        popd
+        pip list
+        echo "::endgroup::"
+
+        echo "::group::Export to ExecuTorch"
+        # Pass matrix variable as environment variable
+        export MODEL_ID="${{ matrix.hf_model_id }}"
+        export OUTPUT_DIR="$(pwd)/${MODEL_ID}_coreml"
+        pushd optimum-executorch
+
+        ARGS=(
+          "--model" "${MODEL_ID}"
+          "--task" "text-generation"
+          "--recipe" "coreml_fp32_gpu"
+          "--qlinear" "4w"
+          "--qembedding" "8w"
+          "--output_dir" "${OUTPUT_DIR}"
+        )
+
+        optimum-cli export executorch "${ARGS[@]}"
+
+        ls -FlAGhp ${OUTPUT_DIR}
+        popd
+        echo "::endgroup::"
+
+        echo "::group::Inference using python API"
+        pushd optimum-executorch
+        python -c "
+        import os
+        from optimum.executorch import ExecuTorchModelForCausalLM
+        from transformers import AutoTokenizer
+
+        model_id = os.getenv('MODEL_ID')
+        pte_dir = os.getenv('OUTPUT_DIR')
+        print(f'Loading model {model_id} from {pte_dir}.')
+        model = ExecuTorchModelForCausalLM.from_pretrained(pte_dir)
+        generated_text = model.text_generation(
+          tokenizer=AutoTokenizer.from_pretrained(model_id),
+          prompt='Simply put, the theory of relativity states that',
+          max_seq_len=64
+        )
+        print(generated_text)
+        "
+        popd
+        echo "::endgroup::"
 
   test-llama-runner-qnn-linux:
     name: test-llama-runner-qnn-linux
