Trying to prevent exit on error from grep, testing fix

diff --git a/.github/workflows/trunk.yml b/.github/workflows/trunk.yml
--- a/.github/workflows/trunk.yml
+++ b/.github/workflows/trunk.yml
@@ -119,22 +119,29 @@ jobs:
             -C cpu0.CFGITCMSZ=15 \
             -C cpu0.CFGDTCMSZ=15 \
             --simlimit 120
+        cat sim.out
 
+        # Disable exit on error
+        set +e
         # Report failure if any of the ouptut verification checks fail
         # store 0 if found (failure), 1 if not (success)
         exit_status=$(grep -F "ERROR" sim.out)
         if [[ "$exit_status" -eq "0" ]]; then
-          cat sim.out
-          exit 1
+            set -e
+            cat sim.out
+            exit 1
         fi
 
         # Report fail if simulation does not complete successfully
         # store 0 if found (success), 1 if not (failure)
         exit_status= $(grep -F "SUCCESS: Program complete, exiting." sim.out)
         if [[ "$exit_status" -eq "1" ]]; then
-          cat sim.out
-          exit 1
+            set -e
+            cat sim.out
+            exit 1
         fi
+        # Re-enable exit on error
+        set -e
 
   test-models-linux-aarch64:
     name: test-models-linux-aarch64
